---
title: "vis_employment"
author: "roland cunha montenegro"
date: "17 Februar 2021"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(extrafont)
library(showtext)

loadfonts()
```

```{r}
#read emplyment data from results
employment_total <- read_excel("report_pivot_merged.xlsx", sheet = "emplmtno_yr")
```

```{r}

# Spread scenarios to be able to change them
employment_diff <- spread(employment_total, key = "Scenario", value = "Value")

# Transform each scenario into the relative difference to reference scenario
employment_diff <- employment_diff %>% mutate(bau = (bau-ref)/ref)
employment_diff <- employment_diff %>% mutate(cAP = (cAP-ref)/ref)
employment_diff <- employment_diff %>% mutate(inv = (inv-ref)/ref)
employment_diff <- employment_diff %>% mutate(lab = (lab-ref)/ref)
employment_diff <- employment_diff %>% mutate(vat = (vat-ref)/ref)
```

```{r}
# drop non-EU regions, years after 2030 and categories that are not 'total'
employment_diff_filter <- filter(employment_diff, grepl('DEU|FRA|ITA|UKI|POL|BNL|ESP|EUN|EUS|EU28', Region))
employment_diff_filter <- filter(employment_diff_filter, grepl('2011|2015|2020|2025|2030', Year))
employment_diff_filter <- filter(employment_diff_filter, Type == 'total')
# drop ref
employment_diff_filter <- subset(employment_diff_filter, select = -c(ref, Type))

# gather scenarios
employment_diff_filter <- gather(employment_diff_filter, 'bau', 'cAP', 'inv', 'vat', 'lab', key = 'Scenario', value = 'Value')

# update scenario names and change order
employment_diff_filter[[3]] = toupper(employment_diff_filter[[3]])

employment_diff_filter$Scenario <- factor(employment_diff_filter$Scenario, levels = c("INV",
                                "CAP",
                                "LAB",
                                "VAT",
                                "BAU"))
```

```{r}
plot_emp <- ggplot(data = filter(employment_diff_filter, Year > 2022), aes(y = Scenario, x = Value))

plot_emp +
  geom_point(alpha = 0.3, size = 2)+
  geom_point(data = filter(employment_diff_filter, Year > 2022 & Region == "EU28"), 
             aes(fill = Region), 
             colour = "blue",
             alpha = 1, 
             size = 3, 
             shape = 21, 
             stroke =2) +
  geom_point(data = filter(employment_diff_filter, Year > 2022 & Region == "DEU"), 
             aes(fill = Region), 
             colour = "black",
             alpha = 1, 
             size = 3, 
             stroke = 2, 
             shape =21) +
  facet_wrap(~Year, ncol =1) +
  scale_x_continuous(name = "Difference to reference scenario [REF]",
                     labels = scales::label_percent(), breaks = seq(-0.02, 0.01,0.002))+
  labs(color = "Region",
       shape = "Region",
       fill = "Region")+
  scale_shape_manual(name = "Regions",
                     labels = c("Germany", "EU-28"),
                     values = c("Germany" = 21, "EU-28" = 21)) +
  scale_colour_manual(name = "Regions",
                     labels = c("Germany", "EU-28"),
                     values = c("red", "blue")) +
  scale_fill_manual(name = "Regions",
                     labels = c("Germany", "EU-28"),
                     values = c("yellow", "blue")) +
  theme_bw()+
  theme(text         = element_text(size=10, family="Palatino Linotype"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        axis.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.position = "bottom")
  
ggsave(width = 7, height = 5, filename = "emp_dev.png")

```
```{r}
employment_diff_filter$Region <- gsub("DEU","Germany", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("FRA","France", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("ITA","Italy", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("UKI","UK", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("POL","Poland", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("ESP","Spain and \nPortugal", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("BNL","Benelux", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("EUN","Northern EU", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("EUS","Central and \nSoutheastern EU", employment_diff_filter$Region)
employment_diff_filter$Region <- gsub("EU28","EU-28", employment_diff_filter$Region)
employment_diff_filter$Scenario <- gsub("VAT","CON", employment_diff_filter$Scenario)



employment_diff_filter$Region <- ordered(employment_diff_filter$Region, levels = c("Germany",
                            "France",
                            "Italy",
                            "UK",
                            "Poland",
                            "Spain and \nPortugal",
                            "Benelux",
                            "Northern EU",
                            "Central and \nSoutheastern EU",
                            "EU-28"))

employment_diff_filter <- employment_diff_filter %>% mutate_each(funs(toupper), Scenario)

employment_diff_filter$Scenario <- ordered(employment_diff_filter$Scenario, levels = c("BAU",
                            "CON",
                            "LAB",
                            "CAP",
                            "INV"))

```

```{r}

plot_emp2 <- ggplot(data = filter(employment_diff_filter, Year == 2030), aes(x = Scenario, y = Value))

plot_emp2 +
  geom_bar(stat = "identity", aes(fill = Scenario), color = "black") +
  facet_wrap(~ Region, nrow = 2) +
  scale_y_continuous(name = "Difference of total employment compared to reference scenario",
                     labels = scales::label_percent(),
                     breaks = seq(-0.015, 0.005,0.0025))+
  scale_fill_brewer(palette="Set1") +
  theme_bw()+
  theme(text         = element_text(size=10, family="Palatino Linotype"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.title.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.position = "bottom")

ggsave(width = 8, height = 6, filename = "emp_2030.png")
```

